// <auto-generated />
using System;
using CafeRadar.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CafeRadar.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251127221133_AddImageUrlToCafes")]
    partial class AddImageUrlToCafes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CafeRadar.Api.Models.Cafe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cafes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Lacina 5, Mostar 88000 Bosnia and Herzegovina",
                            Name = "Mood Bar - Night & Lounge Bar"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Zalik 12, Mostar 88000 Bosnia and Herzegovina",
                            Name = "Caffe Pizzeria Urban Forest"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Fejiceva Bb, Mostar 88000 Bosnia and Herzegovina",
                            Name = "Fabrika Coffee Mostar"
                        });
                });

            modelBuilder.Entity("CafeRadar.Api.Models.Measurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CafeId")
                        .HasColumnType("int");

                    b.Property<string>("LightLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LightValue")
                        .HasColumnType("int");

                    b.Property<DateTime>("MeasuredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiseLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoiseValue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CafeId");

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("CafeRadar.Api.Models.Measurement", b =>
                {
                    b.HasOne("CafeRadar.Api.Models.Cafe", "Cafe")
                        .WithMany("Measurements")
                        .HasForeignKey("CafeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cafe");
                });

            modelBuilder.Entity("CafeRadar.Api.Models.Cafe", b =>
                {
                    b.Navigation("Measurements");
                });
#pragma warning restore 612, 618
        }
    }
}
